build:
  controller:
    replicaCount: 1
    image:
      # use custom image until upstream PR merged https://github.com/knative/build/pull/519
      #repository: gcr.io/knative-releases/github.com/knative/build/cmd/controller@sha256
      repository: rawlingsj/build-controller
      tag: upstream3
    imagePullPolicy: IfNotPresent
    terminationGracePeriodSeconds: 30
    args:
    - -logtostderr
    - -stderrthreshold
    - INFO
    - -creds-image
    - gcr.io/knative-releases/github.com/knative/build/cmd/creds-init@sha256:7492c3a729101066d959281182a1322a4f5e273f2335f3ea47ee7f049cde424c
    - -git-image
    - gcr.io/knative-releases/github.com/knative/build/cmd/git-init@sha256:6186bee422a984b5bc4e5f794c24fc33b430af8e6a8541751a6fde7c4776c079
    - -nop-image
    - gcr.io/knative-releases/github.com/knative/build/cmd/nop@sha256:1acff01d02c30e9a5b2911a06d65b451d62d6ea70091e87032d9e53f356975f7
    resources:
      limits:
      cpu: 200m
      memory: 256Mi
      requests:
      cpu: 100m
      memory: 128Mi
    service:
      type: ClusterIP
      externalPort: 9090
      internalPort: 9090
  auth:
    git:
      username:
      password:
      # username: my-bot
      # password: my-bot-token
tillerNamespace: kube-system
image:
  creds: gcr.io/knative-releases/github.com/knative/build/cmd/creds-init@sha256:7492c3a729101066d959281182a1322a4f5e273f2335f3ea47ee7f049cde424c
  git: gcr.io/knative-releases/github.com/knative/build/cmd/git-init@sha256:6186bee422a984b5bc4e5f794c24fc33b430af8e6a8541751a6fde7c4776c079
  gcs: gcr.io/cloud-builders/gcs-fetcher
  nop: gcr.io/knative-releases/github.com/knative/build/cmd/nop@sha256:1acff01d02c30e9a5b2911a06d65b451d62d6ea70091e87032d9e53f356975f7
